image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git
  except:
    - gh-pages

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run test  # скрипт тестирования

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name pvova21
  - git config --global user.email podrezov08@rambler.ru
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=build --branch=gh-pages --force --verbose